name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Gradle 8.2
      run: |
        sudo apt-get update
        sudo apt-get install wget unzip -y
        wget https://services.gradle.org/distributions/gradle-8.2-bin.zip
        unzip -qq gradle-8.2-bin.zip -d /opt
        echo "/opt/gradle-8.2/bin" >> $GITHUB_PATH

    - name: Build Debug APK
      run: gradle assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
